<?php

namespace AccountBundle\Entity;

/**
 * AccountEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
