<?php

namespace PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentEntityRepository extends EntityRepository
{
    /**
     * Find and return all persisted payments records ordered by account ASC
     *
     * @return array
     */
    public function findAllOrderByIdDesc(): array
    {
        $dql = sprintf(
            'SELECT p FROM %s p ORDER BY p.id DESC',
            $this->getClassName()
        );
        $query = $this->getEntityManager()->createQuery($dql);

        return !empty($query->getResult()) ? $query->getResult() : [];
    }

    /**
     * @param PaymentEntity $paymentEntity
     */
    public function create(PaymentEntity $paymentEntity)
    {
        $this->getEntityManager()->persist($paymentEntity);
        $this->getEntityManager()->flush();
    }
}
