<?php

namespace PaymentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentEntityRepository extends EntityRepository
{
}
