payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /v1

account:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /v1

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
