PaymentBundle\Entity\PaymentEntity:
    type: entity
    table: payments
    repositoryClass: PaymentBundle\Entity\PaymentEntityRepository
    id:
        id:
            type: 'integer'
            generator:
                strategy: 'AUTO'
    fields:
        account:
            type: string
        amount:
            type: float
        toAccount:
            type: string
            length: 255
            column: to_account
        direction:
            type: string
            length: 255
