services:
  payment.payment_manager:
    class: 'PaymentBundle\Manager\PaymentEntityManager'
    arguments: ['@payment.payment_repository', '@account.account_repository']
  payment.payment_repository:
    class: 'PaymentBundle\Entity\PaymentEntityRepository'
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments: ['PaymentBundle:PaymentEntity']