AccountBundle\Entity\AccountEntity:
    type: entity
    table: account
    repositoryClass: AccountBundle\Entity\AccountEntityRepository
    id:
        id:
            type: string
            id: true
            length: 50
    fields:
        owner:
            type: string
            length: 50
        balance:
            type: float
        currency:
            type: string
            length: 50
