services:
    account.account_manager:
        class: 'AccountBundle\Manager\AccountEntityManager'
        arguments: ['@account.account_repository']
    account.account_repository:
        class: 'AccountBundle\Entity\AccountEntityRepository'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AccountBundle:AccountEntity']